### ISSUE TITLE
Origin cap conflict

### ISSUE THREAD

**Issue by taintedvalor** [UltrusBot/AltOriginGui#5]
The alternative menu conflicts with the origin cap mod I can provide details if needed I don't know if this is already known or not

**Comment by taintedvalor** [comment]
[Alternate Origin GUI](https://github.com/UltrusBot/AltOriginGui) is conflicting with [Origin Cap](#).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on io/github/apace100/origins/screen/ChooseOriginScreen::changeGuiPosition with priority 1000 cannot inject into io/github/apace100/origins/screen/ChooseOriginScreen::method_25426()V merged by notstable.origincap.mixin.ChooseOriginScreenMixin with priority 1000 [PREINJECT Applicator Phase -> altorigingui.mixins.json:ChoseOriginScreenMixin from mod altorigingui -> Prepare Injections ->  -> handler$zmo000$altorigingui$changeGuiPosition(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at io.github.apace100.origins.OriginsClient.onInitializeClient(OriginsClient.java:39)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

## Mod list
```
- ad_astra 1.12.7
- additionalentityattributes 1.2.0+1.19 via mythicmetals
- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
- advancementinfo 1.19.1-fabric0.58.5-1.3.1
- adventurez 1.4.18
- alloy_forgery 2.0.20+1.19
- altorigingui 1.0.1
- amecs 1.3.8+mc.1.19-rc2
- amecsapi 1.3.6+mc22w17a via amecs
- animatica 0.5+1.19
- antighost 1.19.1-fabric0.58.5-1.1.5
- apoli 2.6.1 via origins
- appleskin 2.4.1+mc1.19
- architectury 6.5.85
- artifacts 7.1.1+fabric
- automodpack 3.4.4
- auudio 1.0.3
- backpacked 2.2.0
- balm-fabric 4.5.7
- barista 1.19-1.1.2-Fabric
- bclib 2.1.7
- bettercombat 1.7.1+1.19
- betterdeserttemples 1.19.2-Fabric-2.2.2
- betterdungeons 1.19.2-Fabric-3.2.1
- betterend 2.1.6
- betterf3 4.0.0
- betterfortresses 1.19.2-Fabric-1.0.6
- bettermineshafts 1.19.2-Fabric-3.2.0
- bettermounthud 1.2.0
- betternether 7.1.4
- betteroceanmonuments 1.19.2-Fabric-2.1.0
- betterstats 2.9.3+1.19.2
- betterstrongholds 1.19.2-Fabric-3.2.0
- betterwitchhuts 1.19.2-Fabric-2.1.0
- bitsandchisels 2.7.0
- blue_endless_jankson 1.2.1 via owo
- bookshelf 16.3.20
- borderlessmining 1.1.5+1.19
- botarium 1.8.2
- builtinservers 2.0-BETA+1.19
- byg 2.0.1.4
- caffeineconfig 1.0.0+1.17 via sodium-extra
- calio 1.7.0 via apoli
- capes 1.5.2+1.19.2
- cardinal-components 5.0.2
- cardinal-components-base 5.0.2 via puzzleslib
- cardinal-components-block 5.0.2 via puzzleslib
- cardinal-components-chunk 5.0.2 via puzzleslib
- cardinal-components-entity 5.0.2 via puzzleslib
- cardinal-components-item 5.0.2 via cardinal-components
- cardinal-components-level 5.0.2 via cardinal-components
- cardinal-components-scoreboard 5.0.2 via cardinal-components
- cardinal-components-world 5.0.2 via puzzleslib
- carpet 1.4.84
- carryon 2.1.0.20
- cem 0.7.3-1.19
- chat_heads 0.10.20
- chunksfadein 3.0.11-1.19
- chunky 1.3.38
- citresewn 1.1.2+1.19.2
- citresewn-defaults 1.1.2+1.19.2 via citresewn
- cloth-basic-math 0.6.1 via cloth-config
- cloth-config 8.3.103
- cmdkeybind 1.6.0-1.19
- collective 6.65
- colormatic 3.1.2+mc.1.19
- com_electronwill_night-config_core 3.6.6 via corgilib
- com_electronwill_night-config_toml 3.6.6 via corgilib
- com_eliotlash_mclib_mclib 20 via geckolib3
- com_fasterxml_jackson_core_jackson-annotations 2.13.1 via spoornpacks
- com_fasterxml_jackson_core_jackson-core 2.13.1 via spoornpacks
- com_fasterxml_jackson_core_jackson-databind 2.13.1 via spoornpacks
- com_github_figuramc_luaj_luaj-core 3.0.6-figura via figura
- com_github_figuramc_luaj_luaj-jse 3.0.6-figura via figura
- com_github_llamalad7_mixinextras 0.2.0-beta.8 via friendsandfoes
- com_google_code_findbugs_jsr305 3.0.2 via create
- com_hypherionmc_rpcsdk 1.0 via simple-rpc
- com_moandjiezana_toml_toml4j 0.7.2 via chunksfadein
- com_sksamuel_scrimage_scrimage-core 4.0.31 via mru
- completeconfig-base 2.2.0 via cem
- completeconfig-gui-cloth 2.2.0 via cem
- conditional-mixin 0.3.0 via cull-less-leaves
- continuity 2.0.2+1.19
- controlling 10.0+7
- corgilib 1.0.0.34
- craftingtweaks 15.1.8
- create 0.5.1-b-build.1089+mc1.19.2
- creeperoverhaul 2.0.9
- crittersandcompanions 1.19.2-2.0.1
- crowdin-translate 1.4+1.19 via antighost
- cull-less-leaves 1.0.6
- customcredits 1.0
- customportalapi 0.0.1-beta54-1.19 via deeperdarker
- dawn 3.5.0
- deathbackup 3.0
- deathfinder 4.1.2
- debugify 2.8.0
- deeperdarker 1.1.6
- dev_isxander_settxi_settxi-core 2.10.5 via zoomify
- dev_isxander_settxi_settxi-gui 2.10.5 via zoomify
- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.5 via zoomify
- dragonloot 1.1.2
- drippyloadingscreen 2.2.2
- dripstone_fluid_lib 2.0.1 via milk
- dynamicfps 2.2.0
- eatinganimationid 1.9.1
- ec-core 1.3.0-mc1.19.2 via essential_commands
- emi 1.0.19+1.19.2+fabric
- emi_farmersdelight 1.0.1
- emi_loot 0.6.5+1.19
- emicompat 2.0.3
- emiffect 0.1.5+mc1.19.2
- emitrades 1.0.2+mc1.19.2
- enchantinginfuser 4.2.2
- enchantmentsplus 1.1.1+1.19.2
- enchdesc 13.0.14
- enhancedblockentities 0.7.2+1.19.2
- entity_texture_features 4.4.4
- entityculling 1.6.1-mc1.19.2
- essential_commands 0.33.2-mc1.19.2
- exordium 1.0.2-mc1.19.2
- expandability 6.0.0 via artifacts
- extra-mod-integrations 0.1.2+1.19.2
- fabric-api 0.76.0+1.19.2
- fabric-api-base 0.4.15+8f4e8eb390 via figura
- fabric-api-lookup-api-v1 1.6.14+93d8cb8290 via fabric-api
- fabric-biome-api-v1 9.1.1+16f1e31390 via fabric-api
- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90 via fabric-api
- fabric-client-tags-api-v1 1.0.5+b35fea8390 via fabric-api
- fabric-command-api-v1 1.2.16+f71b366f90 via fabric-api
- fabric-command-api-v2 2.2.1+413cbbc790 via figura
- fabric-commands-v0 0.2.33+df3654b390 via fabric-api
- fabric-containers-v0 0.1.41+df3654b390 via fabric-api
- fabric-content-registries-v0 3.5.2+7c6cd14d90 via fabric-api
- fabric-convention-tags-v1 1.3.0+4bc6e26290 via fabric-api
- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
- fabric-data-generation-api-v1 5.3.8+413cbbc790 via fabric-api
- fabric-dimensions-v1 2.1.35+0d0f210290 via fabric-api
- fabric-entity-events-v1 1.5.4+9244241690 via fabric-api
- fabric-events-interaction-v0 0.4.34+562bff6e90 via fabric-api
- fabric-events-lifecycle-v0 0.2.36+df3654b390 via fabric-api
- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
- fabric-item-api-v1 1.6.6+b7d1888890 via fabric-api
- fabric-item-groups-v0 0.3.39+9244241690 via fabric-api
- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via figura
- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
- fabric-language-kotlin 1.10.8+kotlin.1.9.0
- fabric-lifecycle-events-v1 2.2.4+1b46dc7890 via servercore
- fabric-loot-api-v2 1.1.13+83a8659290 via fabric-api
- fabric-loot-tables-v1 1.1.16+9e7660c690 via fabric-api
- fabric-message-api-v1 5.0.7+93d8cb8290 via fabric-api
- fabric-mining-level-api-v1 2.1.24+33fbc73890 via fabric-api
- fabric-models-v0 0.3.21+c6af733c90 via fabric-api
- fabric-networking-api-v1 1.2.11+10eb22f490 via fabric-api
- fabric-networking-v0 0.3.28+df3654b390 via fabric-api
- fabric-object-builder-api-v1 4.2.2+d8ef690890 via fabric-api
- fabric-particles-v1 1.0.14+4d0d570390 via fabric-api
- fabric-permissions-api-v0 0.2-SNAPSHOT via servercore
- fabric-recipe-api-v1 1.0.1+413cbbc790 via fabric-api
- fabric-registry-sync-v0 0.9.32+9244241690 via fabric-api
- fabric-renderer-api-v1 1.2.1+1adbf27790 via fabric-api
- fabric-renderer-indigo 0.8.0+1adbf27790 via fabric-api
- fabric-renderer-registries-v1 3.2.24+df3654b390 via fabric-api
- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690 via fabric-api
- fabric-rendering-fluids-v1 3.0.11+4d0d570390 via fabric-api
- fabric-rendering-v0 1.1.27+df3654b390 via fabric-api
- fabric-rendering-v1 1.12.1+d8ef690890 via fabric-api
- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
- fabric-resource-loader-v0 0.8.4+edbdcddb90 via figura
- fabric-screen-api-v1 1.0.32+4d0d570390 via fabric-api
- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90 via fabric-api
- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
- fabric-textures-v0 1.0.24+aeb40ebe90 via fabric-api
- fabric-transfer-api-v1 2.1.6+413cbbc790 via fabric-api
- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
- fabricloader 0.14.22
- fabricskyboxes 0.7.2+mc1.19.2
- fabrishot 1.9.2
- fancymenu 2.14.9
- farmersdelight 1.19.2-1.3.10
- fastquit 2.1.0+1.19-1.19.2
- ferritecore 5.0.3
- fiber 0.23.0-2 via patchouli
- figura 0.1.2+1.19.2
- fix-keyboard-on-linux 1.0.0
- flywheel 0.6.8.a-5 via create
- fmextension_audio 1.1.1
- forge_tags 3.0 via create
- forgeconfigapiport 4.2.11
- framework 0.6.7
- friendsandfoes 1.8.5
- fsb-interop 1.3.2+mc1.19.2-build.40
- fwaystones 3.0.8+mc1.19.2
- geckolib3 3.1.40
- google-chat 0.4.2
- graveyard 2.3.2
- holdthatchunk 2.0.1
- iceberg 1.0.46
- indium 1.0.9+mc1.19.2
- inventoryhud 3.4.2
- inventoryprofilesnext 1.10.6
- io_github_douira_glsl-transformer 2.0.0-pre13 via iris
- iris 1.6.6
- isxander-main-menu-credits 1.1.1
- itemmodelfix 1.0.3+1.19
- jade 8.7.3
- jadeaddons 3.2.0
- java 17
- kanos_config 0.4.1+1.14.4-1.19.4 via pehkui
- keybind_fix 1.0.0
- konkrete 1.6.1
- kyrptconfig 1.4.14-1.19 via cmdkeybind
- lambdabettergrass 1.3.0+1.19
- lambdynlights 2.2.0+1.19.2
- languagereload 1.5.8+1.19.2
- lazydfu 0.1.3
- legendarytooltips 1.3.3
- libipn 3.0.2
- libjf 3.2.1
- libjf-base 3.2.1 via libjf
- libjf-config-core-v1 3.2.1 via libjf
- libjf-config-legacy-shim 3.2.1 via libjf
- libjf-config-reflect-v1 3.2.1 via libjf
- libjf-config-ui-tiny-v1 3.2.1 via libjf
- libjf-data-manipulation-v0 3.2.1 via libjf
- libjf-data-v0 3.2.1 via libjf
- libjf-translate-v1 3.2.1 via libjf
- libjf-unsafe-v0 3.2.1 via libjf
- libjf-web-v0 3.2.1 via libjf
- litematica 0.12.7
- lootr 0.4.27.67
- malilib 0.13.0
- me_hypherionmc_simplerpc_simple-rpc-common 4.2.20 via simple-rpc
- memoryleakfix 1.1.1
- midnightcontrols 1.7.4+1.19
- midnightlib 1.0.0 via midnightcontrols
- milk 1.0.51 via create
- minecraft 1.19.2
- mixin-conflict-helper 1.2.0
- mixintrace 1.1.1+1.17
- mm 2.3 via porting_lib_base
- modernfix 5.6.1+mc1.19.2
- modmenu 4.2.0-beta.2
- moonlight 1.19.2-2.2.43
- morechathistory 1.1.1
- moremobvariants 1.0.1
- mru 0.1.5+1.19.2
- mythicmetals 0.17.3+1.19.2
- naturalist 3.0.4
- nochatreports 1.19.2-v1.13.12
- nofade 1.18-2.0.1
- nohostilesaroundcampfire 5.4
- notenoughanimations 1.6.2
- numismatic-overhaul 0.2.9+1.19
- omega-config 1.2.2-1.18.1 via graveyard
- opaccreatesupport 1.3.0
- openpartiesandclaims 0.19.3
- optiglue 2.1.2-mc.1.19 via optigui
- optigui 2.1.2
- org_anarres_jcpp 1.4.14 via iris
- org_antlr_antlr4-runtime 4.11.1 via iris
- org_apache_commons_commons-text 1.10.0 via optigui
- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
- org_aperlambda_lambdajcommon 1.8.1 via midnightcontrols
- org_ini4j_ini4j 0.5.4 via optigui
- org_java-websocket_java-websocket 1.5.4 via figura
- org_javassist_javassist 3.29.2-GA via framework
- org_jetbrains_kotlin_kotlin-reflect 1.9.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.9.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.0 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.2 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.2 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1 via fabric-language-kotlin
- org_joml_joml 1.10.4 via sodium
- org_reflections_reflections 0.10.2 via betterdeserttemples
- org_yaml_snakeyaml 1.33 via essential_commands
- origin-cap 1.2
- origins 1.7.1
- origins-plus-plus 2.1.1
- owo 0.9.3+1.19
- paragon 3.0.2 via deeperdarker
- patchouli 1.19.2-77-FABRIC
- paxi 1.19.2-Fabric-3.0.1
- pehkui 3.7.8+1.14.4-1.20.1
- placeholder-api 2.0.0-pre.1+1.19.2 via servercore
- player-animator 1.0.2
- playerabilitylib 1.6.0 via essential_commands
- porting_lib_accessors 2.1.1038+1.19.2 via create
- porting_lib_attributes 2.1.1038+1.19.2 via porting_lib_obj_loader
- porting_lib_base 2.1.1038+1.19.2 via create
- porting_lib_common 2.1.1038+1.19.2 via porting_lib_obj_loader
- porting_lib_constants 2.1.1038+1.19.2 via porting_lib_obj_loader
- porting_lib_entity 2.1.1038+1.19.2 via create
- porting_lib_extensions 2.1.1038+1.19.2 via create
- porting_lib_fake_players 2.1.1038+1.19.2 via create
- porting_lib_lazy_registration 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_loot 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_model_generators 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_model_loader 2.1.1038+1.19.2 via porting_lib_obj_loader
- porting_lib_models 2.1.1038+1.19.2 via porting_lib_base
- porting_lib_networking 2.1.1038+1.19.2 via create
- porting_lib_obj_loader 2.1.1038+1.19.2 via create
- porting_lib_transfer 2.1.1038+1.19.2 via create
- pride 1.1.2+1.19 via lambdynlights
- prism 1.0.3
- promenade 2.7.1
- puzzle 1.4.2-1.19
- puzzle-base 1.4.2-1.19 via puzzle
- puzzle-gui 1.4.2-1.19 via puzzle
- puzzle-models 1.4.2-1.19 via puzzle
- puzzle-splashscreen 1.4.2-1.19 via puzzle
- puzzleslib 4.4.3
- reach-entity-attributes 2.3.0 via mythicmetals
- reeses-sodium-options 1.6.4+mc1.19.2-build.93
- registrate-fabric 1.1.58-MC1.19.2 via create
- resourcefulconfig 1.0.20
- resourcefullib 1.1.24
- rottencreatures 1.0.1
- seasons 2.3+1.19
- seasonsbygcompat 1.0-2.0.1.1
- seasonsdelightcompat 1.0-1.3.9
- seasonsextras 1.2-BETA+1.19
- seasonsterralithcompat 1.0-2.3.7
- serialization_hooks 0.3.26 via porting_lib_base
- servercore 1.3.5+1.19.2
- settxi-gui-yacl 2.10.5 via zoomify
- simple-rpc 3.2.3
- simplyswords 1.47.0-1.19.2
- skinlayers 1.5.2-mc1.19.1
- smarterfarmers 1.19.2-1.7.1
- smoothboot 1.19-1.7.1
- sodium 0.4.4+build.18
- sodium-extra 0.4.16+mc1.19.2-build.90
- sort 1.0.3
- sort_extension 0.0.3
- spectrelib 0.12.3+1.19.2 via veinmining
- spoornpacks 4.3.3-1.19.1
- spruceui 4.1.0+1.19.2 via lambdynlights
- stacc 1.3.4 via bitsandchisels
- starlight 1.1.1+fabric.ae22326
- step-height-entity-attribute 1.0.0 via artifacts
- tcdcommons 2.9.1+1.19.2 via betterstats
- team_reborn_energy 2.2.0 via botarium
- terrablender 2.0.1.166
- terraform-shapes-api-v1 4.0.0 via promenade
- terralith 2.3.10
- things 0.3.0+1.19
- tmc-utils 0.1.2
- travelerstitles 1.19.2-Fabric-3.1.0
- treechop 0.18.3
- trinkets 3.4.2
- veinmining 1.1.1+1.19.2
- visuality 0.5.6
- visualworkbench 4.2.4
- voicechat 1.19.2-2.4.18
- woof 4.0.1-1.19.2
- xaerominimap 23.6.2
- xaeroworldmap 1.32.0
- xp_storage 1.4.3+1.19
- xp_storage_trinkets 0.1+1.19
- yet-another-config-lib 2.2.0-for-1.19.2
- yigd 1.4.9
- yosbr 0.1.2
- yungsapi 1.19.2-Fabric-3.8.9
- yungsbridges 1.19.2-Fabric-3.1.0
- yungsextras 1.19.2-Fabric-3.1.0
- zoomify 2.9.0
```

## Game info
Minecraft Version: 1.19.2
Fabric Loader Version: 0.14.22

*Message autogenerated using [MixinConflictHelper](https://github.com/isXander/MixinConflictHelper)*
